### ISSUE TITLE
Random textinput focus loss

### ISSUE THREAD

**Issue by poVoq** [lianglee/OhYesChat#10]
It seems like text input fields (tinyMCE and others?) start losing focus randomly when this plugin is enabled.
I start typing and at some point it just stops taking the keyboard input until I click with the mouse on the text input window. This happens when using the latest Firefox and the updated TinyMCE plugin.

**Comment by lianglee** [comment]
thanks for report ,

**Comment by lianglee** [comment]
The bug is fixed please download latest version from link below:
http://community.elgg.org/plugins/1601303/1.4/ohyeschat-14
