### ISSUE TITLE
Conditionally extending views will break during caching

### ISSUE THREAD

**Issue by brettp** [lianglee/OhYesChat#2]
In start.php there is this bit of code:

``` php
if(elgg_is_logged_in()){
   elgg_extend_view('page/elements/foot', 'ohyes/chat/bar');
   OhYesChat::loadCss();
   OhYesChat::loadJs();
}
```

This will cause problems when view caching is enabled. You should always extend views, and then put display logic in the views themselves.

**Comment by lianglee** [comment]
Thanks Brett , fixed!
