### ISSUE TITLE
JS Error

### ISSUE THREAD

**Issue by justus-saul** [lianglee/OhYesChat#23]
![screenshot at 13-57-32](https://cloud.githubusercontent.com/assets/5861826/2970663/fb7d8b40-db5e-11e3-9be2-2e3cac650cbe.png)

**Comment by arsalanshah** [comment]
You are using jquery 1.11.0 ? we didn't tested our chat with latest jquery. will look for this error.
Thanks

**Comment by justus-saul** [comment]
Yes, but happens with 1.6.x too:
![screenshot at 14-21-13](https://cloud.githubusercontent.com/assets/5861826/2970885/d45d52d0-db62-11e3-8007-b9e34a9f2d72.png)

**Comment by arsalanshah** [comment]
Fixed thanks
