### ISSUE TITLE
Cannot close chat window in IE

### ISSUE THREAD

**Issue by gerard-kanters** [lianglee/OhYesChat#24]
If you try to close the chat window in Internet Explorer it fails, this has been seen in different versions of IE (9,10 and 11). 

Firefox and Chrome do not have that issue.

**Comment by gerard-kanters** [comment]
Param id in the chat tab (TAB-"+id) is not passed in internet explorer causing an "invalid call. object".

**Comment by lianglee** [comment]
Yup , bug confirmed

**Comment by lianglee** [comment]
Thanks again for fix!
