### ISSUE TITLE
Cannot see my picture

### ISSUE THREAD

**Issue by gerard-kanters** [lianglee/OhYesChat#25]
Noticed that sometimes users cannot see their own icon in a chat. Not 100% sure if this only occurs when having multiple chat windows open. 

In that session however both users cannot see their own icon and do see the user that they are chatting with. It does not seem browser related though.

**Comment by gerard-kanters** [comment]
Closing the chat box and reopening, will show the user icon, but if you type a new message the icon will not appear besides that message. See picture
![disappearing icon](https://cloud.githubusercontent.com/assets/4699801/3325735/5fd2be58-f793-11e3-907d-d803293b7c5d.JPG)

**Comment by arsalanshah** [comment]
Hmm the chat layout is like new facebook chat , so the user who send images can't see own icon.
Yes this is error when OhYesChat fetch messages it shows both user icon.

**Comment by gerard-kanters** [comment]
That must be a bug in FB chat than as well. But it is still inconsistent and good to see your own icon. FB chat makes a distinction between you and the one you are chatting with by different alignment. OhYesChat does not do that and is therefore confusing.

**Comment by arsalanshah** [comment]
Yes the problem is the blue div should automatically resize but i have no idea how to do that but will try.
