### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by gomes2191** [lianglee/OhYesChat#3]
Upon entering the site or change the page color layout achieves more chat after chat site open color back to normal

color blue layout as amended by css chat

![foto1 jpeg](https://f.cloud.github.com/assets/4576117/2317397/f146ce02-a34b-11e3-88af-5fb4f6f2e171.png)

**Comment by gomes2191** [comment]
Chat does not work 100% cpu

![foto1](https://f.cloud.github.com/assets/4576117/2317476/4f8317bc-a34e-11e3-9a43-d0088abe36c7.png)

**Comment by sathish4fri** [comment]
its working fine in my theme . i think so u can check it in snd.sfcircle.com

**Comment by lianglee** [comment]
are you using latest version?

**Comment by sathish4fri** [comment]
@lianglee are u asking me

**Comment by lianglee** [comment]
@sathish4fri  i am asking to @gomes2191  =D 
@gomes2191  Download 1.1. version from 
http://community.elgg.org/plugins/1601303/1.1/ohyeschat-11

**Comment by sathish4fri** [comment]
:dancer:

**Comment by gomes2191** [comment]
Version 1.1 I've used in various themes continues bug 

Cahche updated several times more bugs remain

**Comment by gomes2191** [comment]
Unfortunately I could not make the chat work already downloaded from github and unsuccessfully.

**Comment by lianglee** [comment]
@gomes2191 it just tracked error , it seems your database prefixes is different, i fixed download new version
http://community.elgg.org/plugins/1601303/1.2/ohyeschat-11

**Comment by gomes2191** [comment]
Now it's working

**Comment by lianglee** [comment]
@gomes2191  glad to hear that!
